### PR TITLE
improve-caching

### PR DESCRIPTION
**Pull request by Darkflame72**

### CODE REVIEW

**Comment by Darkflame72** [comment]
It does need to fix

**Comment by Darkflame72** [comment]
@AjayACST can you review this please?

**Review by AjayACST — APPROVED** [review]

**Comment by Darkflame72** [comment]
@AjayACST did you test the code? It is crashing a decent bit.

**Comment by Darkflame72** [comment]
@AjayACST is there anything else to cache?

**Review by AjayACST — APPROVED** [review]

**Pull request merged**
