### PR TITLE
Version 1 release

### PR DESCRIPTION
**Pull request by Darkflame72**

### CODE REVIEW

**Comment by AjayACST** [comment]
Will most of the cogs need to be re written?

**Comment by Darkflame72** [comment]
> Will most of the cogs need to be re written?

parts of them to enable translation

**Comment by AjayACST** [comment]
> 
> 
> > Will most of the cogs need to be re written?
> 
> parts of them to enable translation

Ok we should probably do those first before we merge then

**Comment by Darkflame72** [comment]
> > > Will most of the cogs need to be re written?
> > 
> > 
> > parts of them to enable translation
> 
> Ok we should probably do those first before we merge then

yeah this isn't ready to merge yet

**Comment by Darkflame72** [comment]
@all-contributors please add @AjayACST  for maintenance, code, bug

**Pull request merged**
